const $=id=>document.getElementById(id),storageKey=slug=>`vanventure-text-order-${slug}`;
let stories=[],blocks=[];
function fromStory(story){return story.chapters.flatMap((chapter,chapterIndex)=>chapter.paragraphs.map((paragraph,paragraphIndex)=>({id:`${chapterIndex}-${paragraphIndex}`,chapter:chapter.title[0],text:paragraph[0]})));}
function save(){localStorage.setItem(storageKey($('journey').value),JSON.stringify(blocks));}
function load(){const story=stories.find(s=>s.slug===$('journey').value);try{blocks=JSON.parse(localStorage.getItem(storageKey(story.slug)))||fromStory(story);}catch{blocks=fromStory(story);}render();}
function render(){const list=$('stops');list.replaceChildren();blocks.forEach((block,i)=>{const node=$('stop-template').content.cloneNode(true),article=node.querySelector('.stop');article.dataset.index=i;node.querySelector('.stop-number').textContent=String(i+1).padStart(2,'0');node.querySelectorAll('[data-field]').forEach(el=>{el.value=block[el.dataset.field]||'';el.addEventListener('input',()=>{blocks[i][el.dataset.field]=el.value;save();});});node.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>move(i,b.dataset.action==='up'?-1:1)));list.append(node);});$('message').textContent=`${blocks.length} aktuelle Textabschnitte · Reihenfolge automatisch gespeichert`;}
function move(i,direction){const other=i+direction;if(other<0||other>=blocks.length)return;[blocks[i],blocks[other]]=[blocks[other],blocks[i]];save();render();document.querySelector(`[data-index="${other}"]`)?.scrollIntoView({behavior:'smooth',block:'center'});}
function payload(){return JSON.stringify({reise:$('journey').value,auftrag:'Vorhandene Absätze in dieser Reihenfolge zu Kapiteln zusammenführen, chronologisch neu schreiben und beide Sprachen sowie Homepage aktualisieren.',textabschnitte:blocks.map((b,i)=>({reihenfolge:i+1,ursprung:b.id,kapitel:b.chapter,text:b.text}))},null,2);}
async function copy(){try{await navigator.clipboard.writeText(`Bitte ordne den Reisebericht nach dieser von mir festgelegten Reihenfolge neu:\n\n${payload()}`);$('message').textContent='Kopiert. Füge den Inhalt jetzt im Codex-Chat ein.';}catch{$('message').textContent='Kopieren wurde blockiert. Nutze „Teilen“ oder „Datei speichern“.';}}
async function start(){stories=await fetch('travel-stories.json').then(r=>r.json());for(const story of stories){const o=document.createElement('option');o.value=story.slug;o.textContent=`${story.country[0]} ${story.year}`;$('journey').append(o);}$('journey').addEventListener('change',load);load();}
$('reset').addEventListener('click',()=>{if(confirm('Deine Sortierung verwerfen und die aktuell veröffentlichte Reihenfolge neu laden?')){localStorage.removeItem(storageKey($('journey').value));load();}});
$('copy').addEventListener('click',copy);
$('share').addEventListener('click',async()=>{if(navigator.share)await navigator.share({title:'VanVenture Textreihenfolge',text:payload()});else copy();});
$('download').addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([payload()],{type:'application/json'}));a.download=`${$('journey').value}-textreihenfolge.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});
start().catch(()=>$('message').textContent='Die aktuellen Texte konnten nicht geladen werden. Bitte die Seite neu öffnen.');
