let csrf='';
async function responseJson(response){try{return await response.json();}catch{throw new Error('Der Server hat keine lesbare Antwort geliefert. Bitte erneut versuchen.');}}
async function api(path,method='GET',data){let response;try{response=await fetch('/api/cockpit/'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:data?JSON.stringify(data):undefined});}catch{throw new Error('Die Verbindung zum Cockpit ist fehlgeschlagen. Bitte die Internetverbindung prüfen und erneut versuchen.');}const value=await responseJson(response);if(!response.ok)throw new Error(value.error||'Die Anfrage konnte nicht verarbeitet werden.');return value;}
const $=id=>document.getElementById(id);
function showLoginError(message){$('login-error').textContent=message;$('login-error').hidden=false;}
function clearLoginError(){$('login-error').textContent='';$('login-error').hidden=true;}
function showWorkspaceError(message){$('state').textContent=message;$('state').style.color='#9d2929';}
async function enter(session){csrf=session.csrf;$('user').textContent=session.displayName||session.name;$('login').hidden=true;$('workspace').hidden=false;const data=await api('overview');$('state').textContent=data.connection?'Kanalverbindung bereit.':'Noch kein YouTube-Kanal verbunden.';$('connect-youtube').hidden=data.connection||session.role!=='admin';const fields=[['Implementierungsphase',data.connection?'2':'1'],['Erfasste Videos',String(data.videos)],['Content-Plan-Einträge',String(data.contentItems)],['Freigegebene Context-Einträge',String(data.approvedContextEntries)],['Letzter automatischer Abruf',data.lastSync?.finished_at||'Noch keiner']];$('overview').replaceChildren(...fields.flatMap(([term,value])=>{const dt=document.createElement('dt');dt.textContent=term;const dd=document.createElement('dd');dd.textContent=value;return[dt,dd];}));}
$('connect-youtube').addEventListener('click',async()=>{try{const result=await api('youtube/connect','POST',{});location.assign(result.url);}catch(error){showWorkspaceError(error.message);}});
$('login-form').addEventListener('submit',async event=>{event.preventDefault();clearLoginError();const button=$('login-button'),form=new FormData(event.currentTarget);button.disabled=true;try{const response=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form))});const data=await responseJson(response);if(!response.ok)throw new Error(data.error||'Anmeldung fehlgeschlagen.');await enter(data);}catch(error){showLoginError(error.message);}finally{button.disabled=false;}});
$('logout').addEventListener('click',async()=>{try{await fetch('/api/logout',{method:'POST',headers:{'X-CSRF-Token':csrf,'Content-Type':'application/json'},body:'{}'});}finally{location.reload();}});
(async()=>{try{const response=await fetch('/api/session');if(response.ok)await enter(await responseJson(response));}catch(error){showWorkspaceError(error.message);}})();
