let csrf='',sessionUser=null,currentTab='dashboard',dialogAction=null;
const $=id=>document.getElementById(id);
async function responseJson(response){try{return await response.json();}catch{throw new Error('Der Server hat keine lesbare Antwort geliefert. Bitte erneut versuchen.');}}
async function api(path,method='GET',data){let response;try{response=await fetch('/api/cockpit/'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:data?JSON.stringify(data):undefined});}catch{throw new Error('Die Verbindung zum Cockpit ist fehlgeschlagen. Bitte Internetverbindung prüfen und erneut versuchen.');}const value=await responseJson(response);if(!response.ok)throw new Error(value.error||'Die Anfrage konnte nicht verarbeitet werden.');return value;}
async function downloadAudit(){let response;try{response=await fetch('/api/cockpit/audit/export',{headers:{'X-CSRF-Token':csrf}});}catch{throw new Error('Die Verbindung zum Cockpit ist fehlgeschlagen. Bitte Internetverbindung prüfen und erneut versuchen.');}if(!response.ok){const value=await responseJson(response);throw new Error(value.error||'Der Export konnte nicht erstellt werden.');}const blob=await response.blob(),disposition=response.headers.get('content-disposition')||'',name=/filename="?([^";]+)"?/i.exec(disposition)?.[1]||'vanventure-channel-audit.json',url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();URL.revokeObjectURL(url);}
function node(tag,text,className){const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(className)el.className=className;return el;}
function date(value){return value?new Intl.DateTimeFormat('de-AT',{dateStyle:'medium'}).format(new Date(value)): '—';}
function dateTime(value){return value?new Intl.DateTimeFormat('de-AT',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)): '—';}
function number(value){return new Intl.NumberFormat('de-AT').format(Number(value||0));}
function metric(value,unit=''){return value===null||value===undefined?'—':`${number(value)}${unit}`;}
function comparison(current,previous,unit=''){if(previous===null||previous===undefined)return 'Vorperiode: —';const delta=Number(current||0)-Number(previous||0),prefix=delta>0?'+':'';return `Vorperiode: ${metric(previous,unit)} · ${prefix}${metric(delta,unit)}`;}
function workspaceError(message){$('workspace-error').textContent=message;$('workspace-error').hidden=!message;}
function loginError(message){$('login-error').textContent=message;$('login-error').hidden=!message;}
function item(title,meta,body,click){const el=node('article',undefined,'item');const head=node('div',undefined,'item-head');head.append(node('strong',title),node('span',meta,'muted'));el.append(head);if(body)el.append(node('p',body));if(click){const edit=node('button','Bearbeiten');edit.type='button';edit.addEventListener('click',click);el.append(edit);}return el;}
function showTab(name){currentTab=name;document.querySelectorAll('[data-panel]').forEach(panel=>panel.hidden=panel.dataset.panel!==name);document.querySelectorAll('[data-tab]').forEach(tab=>tab.setAttribute('aria-selected',String(tab.dataset.tab===name)));if(name==='videos')loadVideos();if(name==='planner')loadPlanner();if(name==='context')loadContext();}
async function dashboard(){const selected=Number($('dashboard-period').value)||28,data=await api(`overview?days=${selected}`);$('state').textContent=data.connection?`Kanal verbunden: ${data.connection.channel_title}`:'Noch kein YouTube-Kanal verbunden.';$('export-audit').hidden=!data.connection;$('connect-youtube').hidden=!!data.connection||sessionUser.role!=='admin';$('sync-youtube').hidden=!data.connection||sessionUser.role!=='admin';const syncSettings=await api('sync-settings');$('sync-frequency').value=String(syncSettings.intervalHours);$('sync-frequency-field').hidden=sessionUser.role!=='admin';const frequencyLabel={0:'Nur manuell',12:'Zweimal täglich',24:'Täglich'}[syncSettings.intervalHours],k=data.kpis.current,p=data.kpis.previous;$('data-quality').textContent=data.availableDays<data.periodDays?`Datenbasis: ${data.availableDays} von ${data.periodDays} Tagen verfügbar. Vergleiche können noch unvollständig sein.`:`Datenbasis: vollständige ${data.periodDays} Tage.`;const fields=[['Views',metric(k.views),comparison(k.views,p.views)],['Watchtime',metric(k.watchTimeMinutes,' Min.'),comparison(k.watchTimeMinutes,p.watchTimeMinutes,' Min.')],['Netto-Abos',metric(k.subscribersNet),comparison(k.subscribersNet,p.subscribersNet)],['Impressionen',metric(k.impressions),comparison(k.impressions,p.impressions)],['CTR',k.impressionsCtr===null?'—':`${(k.impressionsCtr*100).toLocaleString('de-AT',{maximumFractionDigits:2})} %`,p.impressionsCtr===null?'Vorperiode: —':`Vorperiode: ${(p.impressionsCtr*100).toLocaleString('de-AT',{maximumFractionDigits:2})} %`],['Letzter Abgleich',dateTime(data.lastSync?.finished_at),frequencyLabel],['Erfasste Videos',String(data.videos),`${data.contentItems} Plan-Einträge`],['Freigegebener Context',String(data.approvedContextEntries),'für Briefings nutzbar']];$('overview').replaceChildren(...fields.map(([label,value,detail])=>{const box=node('div');const dt=node('dt',label);const dd=node('dd',value);box.append(dt,dd,node('small',detail,'muted'));return box;}));const [health,runs,insights]=await Promise.all([api('health'),api('sync-runs'),api('insights')]);if(health.stale)$('state').textContent+=' · Achtung: Der Datenstand ist überfällig.';else if(health.lastRun?.status==='failed')$('state').textContent+=' · Achtung: Der letzte Abgleich ist fehlgeschlagen.';$('sync-runs').replaceChildren(...(runs.items.length?runs.items.map(run=>item(`${run.status==='succeeded'?'Erfolgreich':'Fehlgeschlagen'} · ${run.kind}`,`${dateTime(run.finished_at||run.started_at)} · ${number(run.records_written)} Datensätze`,run.error_detail_safe||'')): [node('p','Noch kein Abgleich protokolliert.','muted')]));$('insights').replaceChildren(...(insights.items.length?insights.items.map(insight=>item(insight.title,insight.level==='action'?'Aktion':'Signal',insight.basis)): [node('p','Noch keine auswertbaren Signale.','muted')]));}
function duration(seconds){if(seconds===null||seconds===undefined)return '—';const minutes=Math.floor(Number(seconds)/60),rest=Number(seconds)%60;return `${minutes}:${String(rest).padStart(2,'0')} Min.`;}
async function openVideo(video){const result=await api(`videos/${encodeURIComponent(video.video_id)}`),entry=result.item;openDialog('Video einordnen',[field('format','Format','select',entry.format,['longform','short','legacy_clip']),field('pillar','Pillar','select',entry.pillar||'',['','van','explore','move','gear','stories']),field('audit_decision','Audit-Entscheidung','select',entry.audit_decision||'',['','keep','repackage','do_not_pursue']),field('reuse_potential','Wiederverwendungspotenzial','select',entry.reuse_potential||'',['','high','medium','low','none'])],async data=>{await api(`videos/${encodeURIComponent(video.video_id)}`,'PUT',data);await loadVideos();});}
async function loadVideos(){const result=await api(`videos?q=${encodeURIComponent($('video-search').value)}`);$('videos').replaceChildren(...(result.items.length?result.items.map(video=>{const el=node('article',undefined,'item video');const image=document.createElement('img');image.alt='';if(video.thumbnail_url)image.src=video.thumbnail_url;const main=node('div');main.append(node('strong',video.title),node('p',`${date(video.published_at)} · ${video.format||'noch nicht zugeordnet'}${video.pillar?` · ${video.pillar}`:''} · ${duration(video.duration_seconds)}`,'muted'));const latest=video.metric_date?`Letzter Tag (${date(video.metric_date)}): ${number(video.views)} Views · ${number(video.watch_time_minutes)} Min.`:'Noch keine Tageswerte verfügbar.';const metrics=node('div',`Öffentlich gesamt: ${video.public_view_count===null?'—':number(video.public_view_count)} Views · ${latest}`, 'video-metrics');const edit=node('button','Einordnen →','video-action');edit.type='button';edit.setAttribute('aria-label',`Video „${video.title}“ einordnen`);edit.addEventListener('click',()=>openVideo(video));el.append(image,main,metrics,edit);return el;}):[node('p','Noch keine Videos erfasst.','muted')]));}
function hoursLabel(entry){const estimate=entry.estimated_hours===null||entry.estimated_hours===undefined?'Schätzung offen':`Plan: ${entry.estimated_hours} h`;const actual=entry.actual_hours===null||entry.actual_hours===undefined?'Ist offen':`Ist: ${entry.actual_hours} h`;return `${estimate} · ${actual}`;}
async function loadPlanner(){const year=Number($('planner-year').value)||new Date().getFullYear();const result=await api(`content?year=${year}`);$('planner-year').value=result.year;$('planner').replaceChildren(...result.items.map(entry=>item(entry.title_working,`Slot ${entry.slot||'—'} · ${entry.status}`,`${entry.pillar||'Pillar offen'} · ${entry.format}${entry.target_publish_date?` · Termin: ${date(entry.target_publish_date)}`:''} · ${hoursLabel(entry)}`,()=>openContent(entry))));}
async function loadContext(){const result=await api('context');$('context').replaceChildren(...(result.items.length?result.items.map(entry=>item(entry.title,`${entry.category} · ${entry.status}`,entry.body.slice(0,220),()=>openContext(entry))):[node('p','Noch keine Einträge angelegt.','muted')]));}
function field(name,label,type,value,options){const labelEl=node('label',label);let control;if(type==='textarea'){control=document.createElement('textarea');control.value=value||'';}else if(type==='select'){control=document.createElement('select');for(const option of options){const el=node('option',option);el.value=option;el.selected=option===value;control.append(el);}}else{control=document.createElement('input');control.type=type||'text';control.value=value||'';}control.name=name;labelEl.append(control);return labelEl;}
function openDialog(title,fields,save){$('dialog-title').textContent=title;$('dialog-fields').replaceChildren(...fields);$('dialog-error').hidden=true;dialogAction=save;$('editor-dialog').showModal();}
function values(){return Object.fromEntries(new FormData($('editor-form')).entries());}
function openContent(entry={planned_year:Number($('planner-year').value)||new Date().getFullYear(),format:'longform',status:'idea',title_working:'',pillar:'',brief:''}){openDialog(entry.id?'Plan-Eintrag bearbeiten':'Plan-Eintrag anlegen',[field('planned_year','Planjahr','number',entry.planned_year),field('slot','Jahres-Slot (1–12, optional)','number',entry.slot),field('title_working','Arbeitstitel','text',entry.title_working),field('format','Format','text',entry.format),field('pillar','Themen-Pillar','text',entry.pillar),field('status','Status','select',entry.status,['idea','validated','briefed','production','scheduled','published','reviewed']),field('target_publish_date','Geplante Veröffentlichung','date',entry.target_publish_date?.slice(0,10)),field('youtube_video_id','YouTube-Video-ID (optional)','text',entry.youtube_video_id),field('brief','Brief','textarea',entry.brief),field('estimated_hours','Geschätzte Produktionszeit (Stunden)','number',entry.estimated_hours),field('actual_hours','Tatsächliche Produktionszeit (Stunden)','number',entry.actual_hours),field('owner','Verantwortung (Benutzername, optional)','text',entry.owner)],async data=>{await api(entry.id?`content/${entry.id}`:'content',entry.id?'PUT':'POST',data);await loadPlanner();dashboard();});}
function openContext(entry={category:'Van / Hymer',status:'draft',title:'',body:''}){openDialog(entry.id?'Context-Eintrag bearbeiten':'Context-Eintrag anlegen',[field('category','Kategorie','select',entry.category,['Van / Hymer','Reisen','Outdoor','MTB','Kajak','Hund','Mission Paris']),field('title','Titel','text',entry.title),field('body','Inhalt','textarea',entry.body),field('status','Freigabestatus','select',entry.status,['draft','approved','archived']),field('source_url','Quelle (URL, optional)','url',entry.source_url),field('effective_from','Gültig ab','date',entry.effective_from?.slice(0,10)),field('effective_to','Gültig bis','date',entry.effective_to?.slice(0,10))],async data=>{await api(entry.id?`context/${entry.id}`:'context',entry.id?'PUT':'POST',data);await loadContext();dashboard();});}
async function enter(session){csrf=session.csrf;sessionUser=session;$('user').textContent=session.displayName||session.name;$('login').hidden=true;$('workspace').hidden=false;const plannerYear=$('planner-year');for(let year=2026;year<=2035;year++){const option=node('option',String(year));option.value=String(year);option.selected=year===2026;plannerYear.append(option);}await dashboard();}
document.querySelectorAll('[data-tab]').forEach(tab=>tab.addEventListener('click',()=>showTab(tab.dataset.tab)));
$('video-search').addEventListener('input',()=>{clearTimeout(window.videoTimer);window.videoTimer=setTimeout(()=>loadVideos().catch(error=>workspaceError(error.message)),250);});
$('planner-year').addEventListener('change',()=>loadPlanner().catch(error=>workspaceError(error.message)));
$('dashboard-period').addEventListener('change',()=>dashboard().catch(error=>workspaceError(error.message)));
$('export-audit').addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;try{await downloadAudit();}catch(error){workspaceError(error.message);}finally{button.disabled=false;}});
$('new-context').addEventListener('click',()=>openContext());
$('connect-youtube').addEventListener('click',async()=>{try{const result=await api('youtube/connect','POST',{});location.assign(result.url);}catch(error){workspaceError(error.message);}});
$('sync-youtube').addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;try{await api('sync','POST',{});await dashboard();}catch(error){workspaceError(error.message);}finally{button.disabled=false;}});
$('sync-frequency').addEventListener('change',async event=>{const select=event.currentTarget;select.disabled=true;try{await api('sync-settings','PUT',{intervalHours:Number(select.value)});await dashboard();}catch(error){workspaceError(error.message);}finally{select.disabled=false;}});
$('editor-form').addEventListener('submit',async event=>{event.preventDefault();try{await dialogAction(values());$('editor-dialog').close();}catch(error){$('dialog-error').textContent=error.message;$('dialog-error').hidden=false;}});$('dialog-cancel').addEventListener('click',()=>$('editor-dialog').close());
$('login-form').addEventListener('submit',async event=>{event.preventDefault();loginError('');const button=$('login-button'),data=Object.fromEntries(new FormData(event.currentTarget));button.disabled=true;try{const response=await fetch('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await responseJson(response);if(!response.ok)throw new Error(result.error||'Anmeldung fehlgeschlagen.');await enter(result);}catch(error){loginError(error.message);}finally{button.disabled=false;}});
$('logout').addEventListener('click',async()=>{try{await fetch('/api/logout',{method:'POST',headers:{'X-CSRF-Token':csrf,'Content-Type':'application/json'},body:'{}'});}finally{location.reload();}});
(async()=>{try{const response=await fetch('/api/session');if(response.ok)await enter(await responseJson(response));}catch(error){workspaceError(error.message);}})();
