export function escape(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function text(tag,pair,cls=''){return `<${tag}${cls?` class="${cls}"`:''} data-de="${escape(pair[0])}" data-en="${escape(pair[1])}">${escape(pair[0])}</${tag}>`;}
function imagePath(path){return /^assets\/(?:[a-zA-Z0-9_-]+\/)*[a-zA-Z0-9_.-]+\.(png|jpe?g|webp)$/i.test(path||'')?'/'+path:'';}
function videos(s){return (s.videos||[]).filter(v=>/^[a-zA-Z0-9_-]{11}$/.test(v[0])).map(v=>`<a class="button button-dark" href="https://www.youtube.com/watch?v=${escape(v[0])}" target="_blank" rel="noopener">${escape(v[1])} ↗</a>`).join('');}
export function renderHomepage(html,stories){
  return html.replace(/<article class="journey">[\s\S]*?<\/article>/g,block=>{
    const story=stories.find(s=>block.includes(`href="${s.slug}.html"`));if(!story)return block;
    block=block.replace(/<p data-de="[^"]*" data-en="[^"]*">[\s\S]*?<\/p>/,text('p',story.subtitle));
    return block.replace(/<details class="trip-details">[\s\S]*?<\/details>/,`<details class="trip-details"><summary data-de="Etappen im Überblick" data-en="Stages at a glance">Etappen im Überblick</summary><div class="trip-story">${story.chapters.map(c=>`<div class="trip-chapter">${text('h4',c.title)}${c.paragraphs.map(p=>text('p',p)).join('')}</div>`).join('')}${videos(story)}</div></details>`);
  });
}
export function renderStory(s,preview=false){
  const chapters=s.chapters.map((c,i)=>`<section class="story-chapter" id="kapitel-${i+1}"><span class="chapter-number">${String(i+1).padStart(2,'0')}</span>${text('h2',c.title)}${c.paragraphs.map(p=>text('p',p)).join('')}${(c.photos||[]).filter(p=>imagePath(p.src)).map(p=>`<figure class="story-photo"><img src="${imagePath(p.src)}" alt="${escape(p.caption[0])}" loading="lazy">${text('figcaption',p.caption)}</figure>`).join('')}</section>`).join('');
  const toc=s.chapters.map((c,i)=>`<a href="#kapitel-${i+1}">${escape(c.title[0])}</a>`).join('');
  return `<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(s.title[0])} | VanVenture</title><meta name="description" content="${escape(s.subtitle[0])}">${preview?'<meta name="robots" content="noindex,nofollow">':''}<link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/travel-stories.css"><link rel="stylesheet" href="/hero-shared.css"></head><body class="story-page"><header class="site-header story-header"><a class="brand" href="/"><img src="/assets/vanventure-logo-transparent.png" alt=""><span>VANVENTURE</span></a><nav><a href="/">Reisearchiv</a><a href="/redaktion">Redaktion</a></nav><button id="language" class="language" aria-label="Switch to English">EN</button></header><main><section class="story-hero">${imagePath(s.hero?.src)?`<img class="story-hero-image" src="${imagePath(s.hero.src)}" alt="${escape(s.hero.alt||'')}">`:''}<div class="story-hero-copy">${text('p',[`${s.country[0]} · ${s.year}${preview?' · ENTWURF':''}`,`${s.country[1]} · ${s.year}${preview?' · DRAFT':''}`],'eyebrow')}${text('h1',s.title)}${text('p',s.subtitle,'story-subtitle')}${text('p',s.meta,'story-meta')}</div></section><div class="story-layout"><aside class="story-sidebar"><nav>${toc}</nav></aside><article class="story-body">${text('p',s.lead,'story-lead')}${chapters}</article></div><section class="story-end"><h2>Die Reise in bewegten Bildern.</h2><div class="story-videos">${videos(s)}</div><a href="/">← Zurück zum Reisearchiv</a></section></main><footer><span>© <span id="year"></span> VanVenture</span><a href="/redaktion">Redaktion · Anmelden</a><span>Travel slow. Go far.</span></footer><script src="/script.js"></script></body></html>`;
}
