const $=id=>document.getElementById(id);let csrf='',editingUser=null;
async function api(path,method='GET',data){const response=await fetch(`/api/${path}`,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:data?JSON.stringify(data):undefined});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.error||'Die Anfrage konnte nicht ausgeführt werden.');return result;}
function message(value){$('users-message').textContent=value;}
function newUser(){editingUser=null;$('user-form').reset();const form=$('user-form').elements;form.name.disabled=false;form.password.required=true;$('user-form-title').textContent='Neuen Benutzer anlegen';}
function editUser(user){editingUser=user.name;const form=$('user-form').elements;form.name.value=user.name;form.name.disabled=true;form.displayName.value=user.display_name||user.name;form.googleEmail.value=user.google_email||'';form.role.value=user.role;form.enabled.checked=user.enabled;form.password.value='';form.password.required=false;$('user-form-title').textContent='Benutzer bearbeiten · Passwort leer lassen, um es beizubehalten';window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});}
async function users(){const list=await api('users');$('user-list').replaceChildren();for(const user of list){const row=document.createElement('div');row.className='user-row';const details=document.createElement('span');details.textContent=`${user.display_name||user.name} · ${user.name} · ${user.role==='admin'?'Administrator':'Redaktion'}${user.enabled?'':' · inaktiv'}`;row.append(details);if(user.google_email){const note=document.createElement('small');note.textContent=`Google: ${user.google_email}${user.google_linked_at?' · bestätigt':''}`;row.append(note);}const action=document.createElement('button');action.type='button';action.textContent='Bearbeiten';action.addEventListener('click',()=>editUser(user));row.append(action);$('user-list').append(row);}}
$('new-user').addEventListener('click',newUser);
$('user-form').addEventListener('submit',async event=>{event.preventDefault();try{const form=$('user-form').elements,data=Object.fromEntries(new FormData($('user-form')));data.enabled=form.enabled.checked;if(editingUser)data.name=editingUser;await api(editingUser?`users/${encodeURIComponent(editingUser)}`:'users',editingUser?'PUT':'POST',data);newUser();await users();message('Benutzer gespeichert. Geänderte Konten müssen sich neu anmelden.');}catch(error){message(error.message);}});
async function start(){try{const session=await api('session');if(session.role!=='admin'){location.replace('/privat');return;}csrf=session.csrf;document.body.classList.add('private-app-shell');newUser();await users();}catch{location.replace('/redaktion');}}start();
