import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';

const scopes=['https://www.googleapis.com/auth/youtube.readonly','https://www.googleapis.com/auth/yt-analytics.readonly'];
function key(){const value=process.env.COCKPIT_TOKEN_ENCRYPTION_KEY;if(!/^[a-f0-9]{64}$/i.test(value||''))throw new Error('Die private Cockpit-Konfiguration ist unvollständig.');return Buffer.from(value,'hex');}
export function ready(){return !!(process.env.GOOGLE_OAUTH_CLIENT_ID&&process.env.GOOGLE_OAUTH_CLIENT_SECRET&&process.env.YOUTUBE_CHANNEL_ID&&/^[a-f0-9]{64}$/i.test(process.env.COCKPIT_TOKEN_ENCRYPTION_KEY||''));}
export function authorizationUrl(state,codeChallenge){const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:process.env.GOOGLE_OAUTH_CLIENT_ID,redirect_uri:process.env.GOOGLE_OAUTH_REDIRECT_URI,response_type:'code',scope:scopes.join(' '),access_type:'offline',prompt:'consent',state,code_challenge:codeChallenge,code_challenge_method:'S256'}).toString();return url.toString();}
export async function exchange(code,codeVerifier){const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:process.env.GOOGLE_OAUTH_CLIENT_ID,client_secret:process.env.GOOGLE_OAUTH_CLIENT_SECRET,redirect_uri:process.env.GOOGLE_OAUTH_REDIRECT_URI,grant_type:'authorization_code',code_verifier:codeVerifier})});if(!response.ok)throw new Error('GOOGLE_TOKEN_EXCHANGE');const token=await response.json();if(typeof token.refresh_token!=='string'||!token.refresh_token)throw new Error('GOOGLE_REFRESH_TOKEN');return token;}
export function seal(value){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv);const data=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return {ciphertext:data.toString('hex'),iv:iv.toString('hex'),tag:cipher.getAuthTag().toString('hex')};}
export function unseal(row){const cipher=createDecipheriv('aes-256-gcm',key(),Buffer.from(row.token_iv,'hex'));cipher.setAuthTag(Buffer.from(row.token_tag,'hex'));return Buffer.concat([cipher.update(Buffer.from(row.token_ciphertext,'hex')),cipher.final()]).toString('utf8');}
async function google(url,token){const response=await fetch(url,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error(response.status===401?'GOOGLE_TOKEN_INVALID':`GOOGLE_API_${response.status}`);return response.json();}
function rows(report){const headers=report.columnHeaders?.map(h=>h.name)||[];return (report.rows||[]).map(row=>Object.fromEntries(headers.map((h,index)=>[h,row[index]])));}
function iso(value){return new Date(value).toISOString().slice(0,10);}
async function analytics(token,params){const url=new URL('https://youtubeanalytics.googleapis.com/v2/reports');url.search=new URLSearchParams({ids:'channel==MINE',...params}).toString();return rows(await google(url,token));}
async function reporting(url,token,options={}){const response=await fetch(url,{...options,headers:{Authorization:`Bearer ${token}`,...(options.headers||{})}});if(!response.ok)throw new Error(`GOOGLE_REPORTING_${response.status}`);return response.json();}
function csv(text){const result=[];let row=[],cell='',quoted=false;for(let index=0;index<text.length;index+=1){const char=text[index],next=text[index+1];if(quoted){if(char==='"'&&next==='"'){cell+='"';index+=1;}else if(char==='"')quoted=false;else cell+=char;continue;}if(char==='"'){quoted=true;continue;}if(char===','){row.push(cell);cell='';continue;}if(char==='\n'){row.push(cell.replace(/\r$/,''));if(row.some(Boolean))result.push(row);row=[];cell='';continue;}cell+=char;}if(cell||row.length){row.push(cell);result.push(row);}return result;}
function ctr(value){const number=Number(value);return Number.isFinite(number)?(number>1?number/100:number):null;}
function reachIndex(reach){return new Map(reach.map(row=>[`${row.video}|${row.day}`,row]));}
function reachByDay(reach){const result=new Map();for(const row of reach){const current=result.get(row.day)||{impressions:0,weightedCtr:0};current.impressions+=row.impressions;current.weightedCtr+=row.impressions*(row.impressionsClickThroughRate||0);result.set(row.day,current);}return new Map([...result].map(([day,value])=>[day,{impressions:value.impressions,impressionsClickThroughRate:value.impressions?value.weightedCtr/value.impressions:null}]));}
export async function inspect(token){const data=await google('https://www.googleapis.com/youtube/v3/channels?part=snippet,contentDetails,statistics&mine=true',token);const channel=data.items?.[0];if(!channel||channel.id!==process.env.YOUTUBE_CHANNEL_ID)throw new Error('GOOGLE_CHANNEL_MISMATCH');return channel;}
export async function refresh(refreshToken){const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({refresh_token:refreshToken,client_id:process.env.GOOGLE_OAUTH_CLIENT_ID,client_secret:process.env.GOOGLE_OAUTH_CLIENT_SECRET,grant_type:'refresh_token'})});if(!response.ok)throw new Error(response.status===400?'GOOGLE_OAUTH_REFRESH_REJECTED':'GOOGLE_REFRESH_FAILED');const token=await response.json();if(typeof token.access_token!=='string')throw new Error('GOOGLE_REFRESH_FAILED');return token.access_token;}
function durationSeconds(value){const match=/^PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/.exec(value||'');return match?(Number(match[1]||0)*3600+Number(match[2]||0)*60+Number(match[3]||0)):null;}
export async function videos(channel,token){const playlist=channel.contentDetails?.relatedPlaylists?.uploads;if(!playlist)return [];const result=[];let pageToken='';do{const url=new URL('https://www.googleapis.com/youtube/v3/playlistItems');url.search=new URLSearchParams({part:'snippet,contentDetails',playlistId:playlist,maxResults:'50',pageToken}).toString();const page=await google(url,token);for(const item of page.items||[]){const id=item.contentDetails?.videoId;if(id)result.push({video_id:id,title:item.snippet?.title||'Ohne Titel',description:item.snippet?.description||'',published_at:item.contentDetails?.videoPublishedAt||null,thumbnail_url:item.snippet?.thumbnails?.medium?.url||item.snippet?.thumbnails?.default?.url||null});}pageToken=page.nextPageToken||'';}while(pageToken&&result.length<500);
  for(let index=0;index<result.length;index+=50){const ids=result.slice(index,index+50).map(video=>video.video_id).join(','),url=new URL('https://www.googleapis.com/youtube/v3/videos');url.search=new URLSearchParams({part:'contentDetails,status,statistics',id:ids,maxResults:'50'}).toString();const details=await google(url,token),byId=new Map((details.items||[]).map(item=>[item.id,item]));for(const video of result){const item=byId.get(video.video_id);if(!item)continue;video.duration_seconds=durationSeconds(item.contentDetails?.duration);video.privacy_status=item.status?.privacyStatus||null;video.public_view_count=item.statistics?.viewCount===undefined?null:Number(item.statistics.viewCount);}}
  return result;}
// Analytics data for the current UTC day is not final and may be rejected with HTTP 400.
// The cockpit therefore always ends the rolling report at the last completed day.
function completedReportingRange(){const end=new Date();end.setUTCHours(0,0,0,0);end.setUTCDate(end.getUTCDate()-1);const start=new Date(end);start.setUTCDate(start.getUTCDate()-364);return {start,end};}
// Thumbnail reach is not a supported targeted Analytics query. YouTube exposes it
// only through a daily Reporting API job (channel_reach_basic_a1).
export async function reachMetrics(token){const jobsUrl='https://youtubereporting.googleapis.com/v1/jobs?pageSize=100';let jobs=(await reporting(jobsUrl,token)).jobs||[],job=jobs.find(item=>item.reportTypeId==='channel_reach_basic_a1');if(!job){try{job=await reporting('https://youtubereporting.googleapis.com/v1/jobs',token,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'VanVenture Cockpit – Thumbnail Reach',reportTypeId:'channel_reach_basic_a1'})});}catch(error){if(error.message!=='GOOGLE_REPORTING_409')throw error;jobs=(await reporting(jobsUrl,token)).jobs||[];job=jobs.find(item=>item.reportTypeId==='channel_reach_basic_a1');}}if(!job)return [];const reports=(await reporting(`https://youtubereporting.googleapis.com/v1/jobs/${encodeURIComponent(job.id)}/reports?pageSize=1000`,token)).reports||[],all=[];for(const report of reports){const response=await fetch(report.downloadUrl,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)continue;const [header,...data]=csv(await response.text()),columns=new Map((header||[]).map((name,index)=>[name,index]));for(const values of data){const day=values[columns.get('date')],video=values[columns.get('video_id')],impressions=Number(values[columns.get('video_thumbnail_impressions')]),impressionsClickThroughRate=ctr(values[columns.get('video_thumbnail_impressions_ctr')]);if(/^\d{4}-\d{2}-\d{2}$/.test(day||'')&&video&&Number.isFinite(impressions))all.push({day,video,impressions,impressionsClickThroughRate});}}return all;}
export async function dailyMetrics(token,reach=[]){const {start,end}=completedReportingRange(),params={startDate:iso(start),endDate:iso(end),dimensions:'day',sort:'day'};const core=(await analytics(token,{...params,metrics:'views,estimatedMinutesWatched,subscribersGained,subscribersLost'})).filter(row=>/^\d{4}-\d{2}-\d{2}$/.test(row.day||'')),byDay=reachByDay(reach);return core.map(row=>({...row,...(byDay.get(row.day)||{})}));}
export async function videoDailyMetrics(videoIds,token,reach=[]){if(!videoIds.length)return [];const {start,end}=completedReportingRange(),result=[],byVideoDay=reachIndex(reach);for(const video of videoIds){const params={startDate:iso(start),endDate:iso(end),dimensions:'day',filters:`video==${video}`,sort:'day'},core=(await analytics(token,{...params,metrics:'views,estimatedMinutesWatched,averageViewDuration,likes,comments'})).filter(row=>/^\d{4}-\d{2}-\d{2}$/.test(row.day||''));result.push(...core.map(row=>({...row,...(byVideoDay.get(`${video}|${row.day}`)||{}),video})));}return result;}
export async function trafficSources(videoIds,token){if(!videoIds.length)return {from_date:null,to_date:null,items:[]};const {start,end}=completedReportingRange(),items=[];for(let index=0;index<videoIds.length;index+=25){const ids=videoIds.slice(index,index+25).join(',');try{const report=await analytics(token,{startDate:iso(start),endDate:iso(end),dimensions:'video,insightTrafficSourceType',metrics:'views,estimatedMinutesWatched',filters:`video==${ids}`,sort:'-views'});items.push(...report.map(row=>({video_id:row.video,source_type:row.insightTrafficSourceType,views:Number(row.views)||0,watch_time_minutes:Number(row.estimatedMinutesWatched)||0})));}catch{ /* Optional Analytics V2 data must never block the core sync. */ }}return {from_date:iso(start),to_date:iso(end),items};}
export async function retention(videoIds,token){const {start,end}=completedReportingRange(),items=[];for(const video of videoIds){try{const report=await analytics(token,{startDate:iso(start),endDate:iso(end),dimensions:'elapsedVideoTimeRatio',metrics:'audienceWatchRatio,relativeRetentionPerformance',filters:`video==${video};audienceType==ORGANIC`,sort:'elapsedVideoTimeRatio'});items.push(...report.map(row=>({video_id:video,elapsed_ratio:Number(row.elapsedVideoTimeRatio),audience_watch_ratio:Number(row.audienceWatchRatio),relative_retention_performance:Number(row.relativeRetentionPerformance)})));}catch{ /* Some videos and reports do not expose retention through the API. */ }}return {from_date:iso(start),to_date:iso(end),items};}
export async function snapshots(candidates,token){const result=[];for(const candidate of candidates){const start=iso(candidate.published_at),end=new Date(candidate.published_at);end.setUTCDate(end.getUTCDate()+candidate.age_days);const values=await analytics(token,{startDate:start,endDate:iso(end),metrics:'views,estimatedMinutesWatched,averageViewDuration,likes,comments',filters:`video==${candidate.video_id}`});result.push({video_id:candidate.video_id,age_days:candidate.age_days,snapshot_date:iso(end),metrics:values[0]||{views:0,estimatedMinutesWatched:0,averageViewDuration:0,likes:0,comments:0},complete:true});}return result;}
export {scopes};
