import { createCipheriv, createDecipheriv, randomBytes } from 'node:crypto';

const scopes=['https://www.googleapis.com/auth/youtube.readonly','https://www.googleapis.com/auth/yt-analytics.readonly'];
function key(){const value=process.env.COCKPIT_TOKEN_ENCRYPTION_KEY;if(!/^[a-f0-9]{64}$/i.test(value||''))throw new Error('Die private Cockpit-Konfiguration ist unvollständig.');return Buffer.from(value,'hex');}
export function ready(){return !!(process.env.GOOGLE_OAUTH_CLIENT_ID&&process.env.GOOGLE_OAUTH_CLIENT_SECRET&&process.env.YOUTUBE_CHANNEL_ID&&/^[a-f0-9]{64}$/i.test(process.env.COCKPIT_TOKEN_ENCRYPTION_KEY||''));}
export function authorizationUrl(state,codeChallenge){const url=new URL('https://accounts.google.com/o/oauth2/v2/auth');url.search=new URLSearchParams({client_id:process.env.GOOGLE_OAUTH_CLIENT_ID,redirect_uri:process.env.GOOGLE_OAUTH_REDIRECT_URI,response_type:'code',scope:scopes.join(' '),access_type:'offline',prompt:'consent',state,code_challenge:codeChallenge,code_challenge_method:'S256'}).toString();return url.toString();}
export async function exchange(code,codeVerifier){const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({code,client_id:process.env.GOOGLE_OAUTH_CLIENT_ID,client_secret:process.env.GOOGLE_OAUTH_CLIENT_SECRET,redirect_uri:process.env.GOOGLE_OAUTH_REDIRECT_URI,grant_type:'authorization_code',code_verifier:codeVerifier})});if(!response.ok)throw new Error('GOOGLE_TOKEN_EXCHANGE');const token=await response.json();if(typeof token.refresh_token!=='string'||!token.refresh_token)throw new Error('GOOGLE_REFRESH_TOKEN');return token;}
export function seal(value){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key(),iv);const data=Buffer.concat([cipher.update(value,'utf8'),cipher.final()]);return {ciphertext:data.toString('hex'),iv:iv.toString('hex'),tag:cipher.getAuthTag().toString('hex')};}
export function unseal(row){const cipher=createDecipheriv('aes-256-gcm',key(),Buffer.from(row.token_iv,'hex'));cipher.setAuthTag(Buffer.from(row.token_tag,'hex'));return Buffer.concat([cipher.update(Buffer.from(row.token_ciphertext,'hex')),cipher.final()]).toString('utf8');}
async function google(url,token){const response=await fetch(url,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok)throw new Error(response.status===401?'GOOGLE_TOKEN_INVALID':`GOOGLE_API_${response.status}`);return response.json();}
function rows(report){const headers=report.columnHeaders?.map(h=>h.name)||[];return (report.rows||[]).map(row=>Object.fromEntries(headers.map((h,index)=>[h,row[index]])));}
function iso(value){return new Date(value).toISOString().slice(0,10);}
async function analytics(token,params){const url=new URL('https://youtubeanalytics.googleapis.com/v2/reports');url.search=new URLSearchParams({ids:'channel==MINE',...params}).toString();return rows(await google(url,token));}
export async function inspect(token){const data=await google('https://www.googleapis.com/youtube/v3/channels?part=snippet,contentDetails,statistics&mine=true',token);const channel=data.items?.[0];if(!channel||channel.id!==process.env.YOUTUBE_CHANNEL_ID)throw new Error('GOOGLE_CHANNEL_MISMATCH');return channel;}
export async function refresh(refreshToken){const response=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({refresh_token:refreshToken,client_id:process.env.GOOGLE_OAUTH_CLIENT_ID,client_secret:process.env.GOOGLE_OAUTH_CLIENT_SECRET,grant_type:'refresh_token'})});if(!response.ok)throw new Error(response.status===400?'GOOGLE_OAUTH_REFRESH_REJECTED':'GOOGLE_REFRESH_FAILED');const token=await response.json();if(typeof token.access_token!=='string')throw new Error('GOOGLE_REFRESH_FAILED');return token.access_token;}
export async function videos(channel,token){const playlist=channel.contentDetails?.relatedPlaylists?.uploads;if(!playlist)return [];const result=[];let pageToken='';do{const url=new URL('https://www.googleapis.com/youtube/v3/playlistItems');url.search=new URLSearchParams({part:'snippet,contentDetails',playlistId:playlist,maxResults:'50',pageToken}).toString();const page=await google(url,token);for(const item of page.items||[]){const id=item.contentDetails?.videoId;if(id)result.push({video_id:id,title:item.snippet?.title||'Ohne Titel',description:item.snippet?.description||'',published_at:item.contentDetails?.videoPublishedAt||null,thumbnail_url:item.snippet?.thumbnails?.medium?.url||item.snippet?.thumbnails?.default?.url||null});}pageToken=page.nextPageToken||'';}while(pageToken&&result.length<500);return result;}
// Analytics data for the current UTC day is not final and may be rejected with HTTP 400.
// The cockpit therefore always ends the rolling report at the last completed day.
function completedReportingRange(){const end=new Date();end.setUTCHours(0,0,0,0);end.setUTCDate(end.getUTCDate()-1);const start=new Date(end);start.setUTCDate(start.getUTCDate()-34);return {start,end};}
export async function dailyMetrics(token){const {start,end}=completedReportingRange(),params={startDate:iso(start),endDate:iso(end),dimensions:'day',sort:'day'};const core=(await analytics(token,{...params,metrics:'views,estimatedMinutesWatched,subscribersGained,subscribersLost'})).filter(row=>/^\d{4}-\d{2}-\d{2}$/.test(row.day||''));let discovery=[];try{discovery=(await analytics(token,{...params,metrics:'impressions,impressionsClickThroughRate'})).filter(row=>/^\d{4}-\d{2}-\d{2}$/.test(row.day||''));}catch(error){if(error.message!=='GOOGLE_API_400')throw error;}const byDay=new Map(discovery.map(row=>[row.day,row]));return core.map(row=>({...row,...(byDay.get(row.day)||{})}));}
export async function videoDailyMetrics(videoIds,token){if(!videoIds.length)return [];const {start,end}=completedReportingRange(),result=[];for(const video of videoIds){const report=await analytics(token,{startDate:iso(start),endDate:iso(end),metrics:'views,estimatedMinutesWatched,averageViewDuration,likes,comments',dimensions:'day',filters:`video==${video}`,sort:'day'});result.push(...report.filter(row=>/^\d{4}-\d{2}-\d{2}$/.test(row.day||'')).map(row=>({...row,video})));}return result;}
export async function snapshots(candidates,token){const result=[];for(const candidate of candidates){const start=iso(candidate.published_at),end=new Date(candidate.published_at);end.setUTCDate(end.getUTCDate()+candidate.age_days);const values=await analytics(token,{startDate:start,endDate:iso(end),metrics:'views,estimatedMinutesWatched,averageViewDuration,likes,comments',filters:`video==${candidate.video_id}`});result.push({video_id:candidate.video_id,age_days:candidate.age_days,snapshot_date:iso(end),metrics:values[0]||{views:0,estimatedMinutesWatched:0,averageViewDuration:0,likes:0,comments:0},complete:true});}return result;}
export {scopes};
